--Create Database
DROP DATABASE IF EXISTS LIBRARY_DB_P2
CREATE DATABASE LIBRARY_DB_P2;

-- Create tables
-- BRANCH TABLE
DROP TABLE IF EXISTS BRANCH;
CREATE TABLE BRANCH(
BRANCH_ID VARCHAR(10) PRIMARY KEY,
MANAGER_ID	VARCHAR(10),
BRANCH_ADDRESS VARCHAR(30),
CONTACT_NO VARCHAR(10)
CHECK (LENGTH(CONTACT_NO)=10 AND CONTACT_NO NOT LIKE '%^[0-9]%')
);

-- EMPLOYEES TABLE
DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES(
EMP_ID VARCHAR(10) PRIMARY KEY,
EMP_NAME VARCHAR(30),
POSITION VARCHAR(30),
SALARY DECIMAL(10,2),
BRANCH_ID VARCHAR(10),
FOREIGN KEY (BRANCH_ID) REFERENCES BRANCH(BRANCH_ID)
);

-- MEMBERS TABLE
DROP TABLE IF EXISTS MEMBERS;
CREATE TABLE MEMBERS(
MEMBER_ID VARCHAR(10) PRIMARY KEY,
MEMBER_NAME VARCHAR(30),
MEMBER_ADDRESS VARCHAR(30),
REG_DATE DATE
);

-- BOOKS TABLE
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
BOOK_ID VARCHAR(50) PRIMARY KEY,
BOOK_TITLE VARCHAR(80),
CATEGORY VARCHAR(30),
RENTAL_PRICE DECIMAL(10,2),
STATUS VARCHAR(10),
AUTHOR VARCHAR(30),
PUBLISHER VARCHAR(30)
);

-- ISSUE_STATUS TABLE
DROP TABLE IF EXISTS ISSUE_STATUS;
CREATE TABLE ISSUE_STATUS(
ISSUED_ID VARCHAR(10) PRIMARY KEY,
ISSUED_MEMBER_ID VARCHAR(30),
ISSUED_BOOK_NAME VARCHAR(50),
ISSUED_DATE DATE,
ISSUED_BOOK_BOOKID VARCHAR(50),
ISSUED_EMP_ID VARCHAR(10),
FOREIGN KEY (ISSUED_MEMBER_ID) REFERENCES MEMBERS(MEMBER_ID),
FOREIGN KEY (ISSUED_BOOK_BOOKID) REFERENCES BOOKS(BOOK_ID),
FOREIGN KEY (ISSUED_EMP_ID) REFERENCES EMPLOYEES(EMP_ID)
);

-- RETURN_STATUS TABLE
DROP TABLE IF EXISTS RETURN_STATUS;
CREATE TABLE RETURN_STATUS(
RETURN_ID VARCHAR(10) PRIMARY KEY,
ISSUED_ID VARCHAR(30),
RETURN_BOOK_NAME VARCHAR(80),
RETURN_DATE DATE,
RETURN_BOOK_BOOKID VARCHAR(50),
FOREIGN KEY (ISSUED_ID) REFERENCES ISSUE_STATUS(ISSUED_ID),
FOREIGN KEY (RETURN_BOOK_BOOKID) REFERENCES BOOKS(BOOK_ID)
);

SELECT * FROM BRANCH;
SELECT * FROM EMPLOYEES;
SELECT * FROM MEMBERS;
SELECT * FROM BOOKS;
SELECT * FROM ISSUE_STATUS;
SELECT * FROM RETURN_STATUS;